from typing import Dict, Optional, Callable

FRAMEWORK_TEMPLATES: Dict[str, Dict] = {
    # === BACKEND WEB (28) ===
    "nodejs_express": {
        "name": "Node.js Express",
        "category": "Backend Web",
        "description": "Servidor Express con estructura MVC",
        "generator": "nodejs",
        "arch": "MVC",
        "testing": "Jest",
        "ci": "GitHub Actions",
    },
    "nodejs_fastify": {
        "name": "Node.js Fastify",
        "category": "Backend Web",
        "description": "Servidor Fastify de alto rendimiento",
        "generator": "nodejs",
        "arch": "Route-based",
        "testing": "Jest",
        "ci": "GitHub Actions",
    },
    "nodejs_nest": {
        "name": "NestJS",
        "category": "Backend Web",
        "description": "Framework Node.js escalable con TypeScript",
        "generator": "nodejs",
        "arch": "Modular/DDD",
        "testing": "Jest",
        "ci": "GitHub Actions",
    },
    "nodejs_koa": {
        "name": "Node.js Koa",
        "category": "Backend Web",
        "description": "Framework Koa.js moderno",
        "generator": "nodejs",
        "arch": "Middleware",
        "testing": "Jest",
        "ci": "GitHub Actions",
    },
    "nodejs_hapi": {
        "name": "Node.js Hapi",
        "category": "Backend Web",
        "description": "Framework Hapi.js configurable",
        "generator": "nodejs",
        "arch": "Plugin-based",
        "testing": "Jest",
        "ci": "GitHub Actions",
    },
    "python_fastapi": {
        "name": "Python FastAPI",
        "category": "Backend Web",
        "description": "API moderna y rápida con Python",
        "generator": "python",
        "arch": "Router/DDD",
        "testing": "Pytest",
        "ci": "GitHub Actions",
    },
    "python_flask": {
        "name": "Python Flask",
        "category": "Backend Web",
        "description": "Microframework Python ligero",
        "generator": "python",
        "arch": "Blueprint",
        "testing": "Pytest",
        "ci": "GitHub Actions",
    },
    "python_django": {
        "name": "Python Django",
        "category": "Backend Web",
        "description": "Framework Python completo MVC",
        "generator": "python",
        "arch": "MVT",
        "testing": "Pytest",
        "ci": "GitHub Actions",
    },
    "python_aiohttp": {
        "name": "Python Aiohttp",
        "category": "Backend Web",
        "description": "Async HTTP para Python",
        "generator": "python",
        "arch": "Handler-based",
        "testing": "Pytest",
        "ci": "GitHub Actions",
    },
    "python_tornado": {
        "name": "Python Tornado",
        "category": "Backend Web",
        "description": "Framework async Python",
        "generator": "python",
        "arch": "RequestHandler",
        "testing": "Pytest",
        "ci": "GitHub Actions",
    },
    "python_starlette": {
        "name": "Python Starlette",
        "category": "Backend Web",
        "description": "ASGI framework Python",
        "generator": "python",
        "arch": "Path-based",
        "testing": "Pytest",
        "ci": "GitHub Actions",
    },
    "go_gin": {
        "name": "Go Gin",
        "category": "Backend Web",
        "description": "Framework web Go rápido",
        "generator": "go",
        "arch": "Router",
        "testing": "Go test",
        "ci": "GitHub Actions",
    },
    "go_fiber": {
        "name": "Go Fiber",
        "category": "Backend Web",
        "description": "Framework Go inspirado en Express",
        "generator": "go",
        "arch": "Middleware",
        "testing": "Go test",
        "ci": "GitHub Actions",
    },
    "go_standard": {
        "name": "Go Standard",
        "category": "Backend Web",
        "description": "Servidor HTTP Go estándar",
        "generator": "go",
        "arch": "Handler",
        "testing": "Go test",
        "ci": "GitHub Actions",
    },
    "go_echo": {
        "name": "Go Echo",
        "category": "Backend Web",
        "description": "Framework Go minimalista",
        "generator": "go",
        "arch": "Router",
        "testing": "Go test",
        "ci": "GitHub Actions",
    },
    "go_chi": {
        "name": "Go Chi",
        "category": "Backend Web",
        "description": "Router Go lightweight",
        "generator": "go",
        "arch": "Router",
        "testing": "Go test",
        "ci": "GitHub Actions",
    },
    "dotnet_aspnet": {
        "name": ".NET 8 ASP.NET Core",
        "category": "Backend Web",
        "description": "Framework web moderno Microsoft",
        "generator": "dotnet",
        "arch": "MVC/API",
        "testing": "xUnit",
        "ci": "GitHub Actions",
    },
    "dotnet_fastEndpoints": {
        "name": ".NET FastEndpoints",
        "category": "Backend Web",
        "description": "Minimal API framework .NET",
        "generator": "dotnet",
        "arch": "Endpoint-based",
        "testing": "xUnit",
        "ci": "GitHub Actions",
    },
    "rust_actix": {
        "name": "Rust Actix",
        "category": "Backend Web",
        "description": "Framework Rust Actor",
        "generator": "rust",
        "arch": "Actor",
        "testing": "Rust test",
        "ci": "GitHub Actions",
    },
    "rust_axum": {
        "name": "Rust Axum",
        "category": "Backend Web",
        "description": "Framework Rust ergonomic",
        "generator": "rust",
        "arch": "Handler",
        "testing": "Rust test",
        "ci": "GitHub Actions",
    },
    "rust_warp": {
        "name": "Rust Warp",
        "category": "Backend Web",
        "description": "Servidor web Rust composable",
        "generator": "rust",
        "arch": "Filter",
        "testing": "Rust test",
        "ci": "GitHub Actions",
    },
    "rust_rocket": {
        "name": "Rust Rocket",
        "category": "Backend Web",
        "description": "Framework Rust simple",
        "generator": "rust",
        "arch": "Route",
        "testing": "Rust test",
        "ci": "GitHub Actions",
    },
    "scala_akka": {
        "name": "Scala Akka HTTP",
        "category": "Backend Web",
        "description": "Framework reactivo Scala",
        "generator": "scala",
        "arch": "Actor",
        "testing": "ScalaTest",
        "ci": "GitHub Actions",
    },
    "scala_play": {
        "name": "Scala Play",
        "category": "Backend Web",
        "description": "Framework Scala full-stack",
        "generator": "scala",
        "arch": "MVC",
        "testing": "ScalaTest",
        "ci": "GitHub Actions",
    },
    "java_spring": {
        "name": "Java Spring Boot",
        "category": "Backend Web",
        "description": "Framework Java enterprise",
        "generator": "java",
        "arch": "MVC",
        "testing": "JUnit",
        "ci": "GitHub Actions",
    },
    "java_quarkus": {
        "name": "Java Quarkus",
        "category": "Backend Web",
        "description": "Java cloud-native",
        "generator": "java",
        "arch": "CDI",
        "testing": "JUnit",
        "ci": "GitHub Actions",
    },
    "kotlin_spring": {
        "name": "Kotlin Spring",
        "category": "Backend Web",
        "description": "Spring Boot con Kotlin",
        "generator": "kotlin",
        "arch": "MVC",
        "testing": "JUnit",
        "ci": "GitHub Actions",
    },
    "kotlin_ktor": {
        "name": "Kotlin Ktor",
        "category": "Backend Web",
        "description": "Framework Kotlin async",
        "generator": "kotlin",
        "arch": "Route",
        "testing": "JUnit",
        "ci": "GitHub Actions",
    },
    # === BACKEND ADICIONALES (10) ===
    "php_laravel": {
        "name": "PHP Laravel",
        "category": "Backend Web",
        "description": "Framework PHP elegante",
        "generator": "php",
        "arch": "MVC",
        "testing": "PHPUnit",
        "ci": "GitHub Actions",
    },
    "php_symfony": {
        "name": "PHP Symfony",
        "category": "Backend Web",
        "description": "Framework PHP reutilizable",
        "generator": "php",
        "arch": "MVC",
        "testing": "PHPUnit",
        "ci": "GitHub Actions",
    },
    "php_slim": {
        "name": "PHP Slim",
        "category": "Backend Web",
        "description": "Microframework PHP",
        "generator": "php",
        "arch": "Router",
        "testing": "PHPUnit",
        "ci": "GitHub Actions",
    },
    "ruby_rails": {
        "name": "Ruby on Rails",
        "category": "Backend Web",
        "description": "Framework Ruby full-stack",
        "generator": "ruby",
        "arch": "MVC",
        "testing": "RSpec",
        "ci": "GitHub Actions",
    },
    "ruby_sinatra": {
        "name": "Ruby Sinatra",
        "category": "Backend Web",
        "description": "Microframework Ruby",
        "generator": "ruby",
        "arch": "Route",
        "testing": "RSpec",
        "ci": "GitHub Actions",
    },
    "elixir_phoenix": {
        "name": "Elixir Phoenix",
        "category": "Backend Web",
        "description": "Framework Elixir web",
        "generator": "elixir",
        "arch": "MVC",
        "testing": "ExUnit",
        "ci": "GitHub Actions",
    },
    "haskell_servant": {
        "name": "Haskell Servant",
        "category": "Backend Web",
        "description": "API type-safe Haskell",
        "generator": "haskell",
        "arch": "Type-level",
        "testing": "Hspec",
        "ci": "GitHub Actions",
    },
    "cpp_rest": {
        "name": "C++ REST SDK",
        "category": "Backend Web",
        "description": "C++ async HTTP",
        "generator": "cpp",
        "arch": "Async",
        "testing": "Catch2",
        "ci": "GitHub Actions",
    },
    "nim_jester": {
        "name": "Nim Jester",
        "category": "Backend Web",
        "description": "Framework Nim web",
        "generator": "nim",
        "arch": "Route",
        "testing": "Unittest",
        "ci": "GitHub Actions",
    },
    "dart_aqueduct": {
        "name": "Dart Aqueduct",
        "category": "Backend Web",
        "description": "Framework Dart server",
        "generator": "dart",
        "arch": "Router",
        "testing": "Test",
        "ci": "GitHub Actions",
    },
    # === FRONTEND WEB (15) ===
    "nextjs_app": {
        "name": "Next.js 14 App Router",
        "category": "Frontend Web",
        "description": "React framework con App Router",
        "generator": "nextjs",
        "arch": "App Router/SSR",
        "testing": "Jest",
        "ci": "GitHub Actions",
    },
    "nextjs_pages": {
        "name": "Next.js 14 Pages Router",
        "category": "Frontend Web",
        "description": "React framework con Pages Router",
        "generator": "nextjs",
        "arch": "Pages/SSR",
        "testing": "Jest",
        "ci": "GitHub Actions",
    },
    "nextjs_standalone": {
        "name": "Next.js Standalone",
        "category": "Frontend Web",
        "description": "Next.js con output standalone",
        "generator": "nextjs",
        "arch": "App Router",
        "testing": "Jest",
        "ci": "GitHub Actions",
    },
    "react_cra": {
        "name": "React Create React App",
        "category": "Frontend Web",
        "description": "SPA React estándar",
        "generator": "react",
        "arch": "SPA",
        "testing": "Jest",
        "ci": "GitHub Actions",
    },
    "react_vite": {
        "name": "React Vite",
        "category": "Frontend Web",
        "description": "React con Vite bundler",
        "generator": "react",
        "arch": "SPA",
        "testing": "Vitest",
        "ci": "GitHub Actions",
    },
    "react_remix": {
        "name": "React Remix",
        "category": "Frontend Web",
        "description": "Full-stack React",
        "generator": "react",
        "arch": "SSR/Edge",
        "testing": "Jest",
        "ci": "GitHub Actions",
    },
    "vue_vite": {
        "name": "Vue.js 3 Vite",
        "category": "Frontend Web",
        "description": "Vue 3 con Vite",
        "generator": "vue",
        "arch": "SPA",
        "testing": "Vitest",
        "ci": "GitHub Actions",
    },
    "vue_nuxt": {
        "name": "Nuxt.js 3",
        "category": "Frontend Web",
        "description": "Vue meta-framework",
        "generator": "vue",
        "arch": "SSR/SSG",
        "testing": "Vitest",
        "ci": "GitHub Actions",
    },
    "svelte_vite": {
        "name": "Svelte Vite",
        "category": "Frontend Web",
        "description": "Svelte con Vite",
        "generator": "svelte",
        "arch": "SPA",
        "testing": "Vitest",
        "ci": "GitHub Actions",
    },
    "sveltekit": {
        "name": "SvelteKit",
        "category": "Frontend Web",
        "description": "Framework Svelte full-stack",
        "generator": "svelte",
        "arch": "SSR/SSG",
        "testing": "Vitest",
        "ci": "GitHub Actions",
    },
    "angular": {
        "name": "Angular 17+",
        "category": "Frontend Web",
        "description": "Framework Google moderno",
        "generator": "angular",
        "arch": "Component",
        "testing": "Jasmine",
        "ci": "GitHub Actions",
    },
    "solid_vite": {
        "name": "SolidJS Vite",
        "category": "Frontend Web",
        "description": "SolidJS con Vite",
        "generator": "solid",
        "arch": "Signal-based",
        "testing": "Vitest",
        "ci": "GitHub Actions",
    },
    "alpine": {
        "name": "Alpine.js",
        "category": "Frontend Web",
        "description": "JS reactivo ligero",
        "generator": "alpine",
        "arch": "Declarative",
        "testing": "None",
        "ci": "GitHub Actions",
    },
    "htmx": {
        "name": "HTMX",
        "category": "Frontend Web",
        "description": "HTML moderno con hipermedia",
        "generator": "htmx",
        "arch": "HATEOAS",
        "testing": "None",
        "ci": "GitHub Actions",
    },
    "qwik": {
        "name": "Qwik",
        "category": "Frontend Web",
        "description": "Framework resumable",
        "generator": "qwik",
        "arch": "Resumable",
        "testing": "Vitest",
        "ci": "GitHub Actions",
    },
    # === MÓVIL (10) ===
    "flutter": {
        "name": "Flutter",
        "category": "Móvil",
        "description": "UI toolkit multiplataforma",
        "generator": "flutter",
        "arch": "Widget",
        "testing": "Flutter Test",
        "ci": "GitHub Actions",
    },
    "react_native": {
        "name": "React Native",
        "category": "Móvil",
        "description": "Apps nativas con React",
        "generator": "react_native",
        "arch": "Component",
        "testing": "Jest",
        "ci": "GitHub Actions",
    },
    "expo": {
        "name": "Expo SDK 50+",
        "category": "Móvil",
        "description": "React Native simplificado",
        "generator": "expo",
        "arch": "Component",
        "testing": "Jest",
        "ci": "GitHub Actions",
    },
    "ionic": {
        "name": "Ionic 7+",
        "category": "Móvil",
        "description": "Apps híbridas HTML/CSS/JS",
        "generator": "ionic",
        "arch": "Component",
        "testing": "Jest",
        "ci": "GitHub Actions",
    },
    "capacitor": {
        "name": "Capacitor 5+",
        "category": "Móvil",
        "description": "Apps web nativas",
        "generator": "capacitor",
        "arch": "Web Native",
        "testing": "Jest",
        "ci": "GitHub Actions",
    },
    "kotlin_android": {
        "name": "Kotlin Android",
        "category": "Móvil",
        "description": "App Android nativa",
        "generator": "kotlin_android",
        "arch": "MVVM",
        "testing": "JUnit",
        "ci": "GitHub Actions",
    },
    "kotlin_compose": {
        "name": "Jetpack Compose",
        "category": "Móvil",
        "description": "UI toolkit Android",
        "generator": "kotlin_android",
        "arch": "Compose",
        "testing": "JUnit",
        "ci": "GitHub Actions",
    },
    "swift_ios": {
        "name": "SwiftUI iOS",
        "category": "Móvil",
        "description": "App iOS nativa SwiftUI",
        "generator": "swift_ios",
        "arch": "SwiftUI",
        "testing": "XCTest",
        "ci": "GitHub Actions",
    },
    "swift_uiKit": {
        "name": "UIKit iOS",
        "category": "Móvil",
        "description": "App iOS UIKit",
        "generator": "swift_ios",
        "arch": "MVC/MVVM",
        "testing": "XCTest",
        "ci": "GitHub Actions",
    },
    "tauri": {
        "name": "Tauri 2.0",
        "category": "Móvil",
        "description": "Apps desktop/móvil web",
        "generator": "tauri",
        "arch": "Web Native",
        "testing": "Vitest",
        "ci": "GitHub Actions",
    },
    # === BLOCKCHAIN (8) ===
    "solidity_hardhat": {
        "name": "Solidity Hardhat",
        "category": "Blockchain",
        "description": "Smart contracts con Hardhat",
        "generator": "solidity",
        "arch": "Contract",
        "testing": "Hardhat Test",
        "ci": "GitHub Actions",
    },
    "solidity_truffle": {
        "name": "Solidity Truffle",
        "category": "Blockchain",
        "description": "Smart contracts con Truffle",
        "generator": "solidity",
        "arch": "Contract",
        "testing": "Mocha",
        "ci": "GitHub Actions",
    },
    "solidity_foundry": {
        "name": "Solidity Foundry",
        "category": "Blockchain",
        "description": "Smart contracts con Foundry",
        "generator": "solidity",
        "arch": "Contract",
        "testing": "Forge",
        "ci": "GitHub Actions",
    },
    "rust_substrate": {
        "name": "Rust Substrate",
        "category": "Blockchain",
        "description": "Blockchain framework Polkadot",
        "generator": "rust_substrate",
        "arch": "Runtime",
        "testing": "Substrate Test",
        "ci": "GitHub Actions",
    },
    "solana_rust": {
        "name": "Solana Rust",
        "category": "Blockchain",
        "description": "Programas Solana",
        "generator": "solana",
        "arch": "Program",
        "testing": "Solana Test",
        "ci": "GitHub Actions",
    },
    "near_rust": {
        "name": "NEAR Rust",
        "category": "Blockchain",
        "description": "Smart contracts NEAR",
        "generator": "near",
        "arch": "Contract",
        "testing": "Near Test",
        "ci": "GitHub Actions",
    },
    "algorand_teal": {
        "name": "Algorand TEAL",
        "category": "Blockchain",
        "description": "Smart contracts Algorand",
        "generator": "algorand",
        "arch": "TEAL",
        "testing": "PyTEAL",
        "ci": "GitHub Actions",
    },
    "cardano_smart": {
        "name": "Cardano Plutus",
        "category": "Blockchain",
        "description": "Smart contracts Cardano",
        "generator": "cardano",
        "arch": "Plutus",
        "testing": "Plutus Test",
        "ci": "GitHub Actions",
    },
    # === DEVOPS / INFRA (15) ===
    "docker": {
        "name": "Docker",
        "category": "DevOps",
        "description": "Contenedores Docker",
        "generator": "docker",
        "arch": "Container",
        "testing": "None",
        "ci": "None",
    },
    "docker_compose": {
        "name": "Docker Compose",
        "category": "DevOps",
        "description": "Multi-contenedor Docker",
        "generator": "docker_compose",
        "arch": "Orchestration",
        "testing": "None",
        "ci": "None",
    },
    "kubernetes": {
        "name": "Kubernetes",
        "category": "DevOps",
        "description": "Orquestación K8s",
        "generator": "kubernetes",
        "arch": "Declarative",
        "testing": "None",
        "ci": "None",
    },
    "helm": {
        "name": "Helm 3",
        "category": "DevOps",
        "description": "Charts Kubernetes",
        "generator": "helm",
        "arch": "Package",
        "testing": "None",
        "ci": "None",
    },
    "kustomize": {
        "name": "Kustomize",
        "category": "DevOps",
        "description": "K8s customization",
        "generator": "kustomize",
        "arch": "Overlay",
        "testing": "None",
        "ci": "None",
    },
    "ansible": {
        "name": "Ansible",
        "category": "DevOps",
        "description": "Automatización Ansible",
        "generator": "ansible",
        "arch": "Idempotent",
        "testing": "Molecule",
        "ci": "GitHub Actions",
    },
    "terraform": {
        "name": "Terraform AWS",
        "category": "DevOps",
        "description": "IaC Terraform AWS",
        "generator": "terraform",
        "arch": "Declarative",
        "testing": "Terratest",
        "ci": "GitHub Actions",
    },
    "terragrunt": {
        "name": "Terragrunt",
        "category": "DevOps",
        "description": "Terraform DRY",
        "generator": "terraform",
        "arch": "DRY",
        "testing": "Terratest",
        "ci": "GitHub Actions",
    },
    "packer": {
        "name": "Packer",
        "category": "DevOps",
        "description": "Imágenes Packer",
        "generator": "packer",
        "arch": "Immutable",
        "testing": "None",
        "ci": "None",
    },
    "vault": {
        "name": "HashiCorp Vault",
        "category": "DevOps",
        "description": "Secrets management",
        "generator": "vault",
        "arch": "Secret Store",
        "testing": "None",
        "ci": "None",
    },
    "jenkins": {
        "name": "Jenkins Pipeline",
        "category": "DevOps",
        "description": "CI/CD Jenkins",
        "generator": "jenkins",
        "arch": "Pipeline",
        "testing": "None",
        "ci": "None",
    },
    "github_actions": {
        "name": "GitHub Actions",
        "category": "DevOps",
        "description": "CI/CD GitHub",
        "generator": "github_actions",
        "arch": "Workflow",
        "testing": "None",
        "ci": "None",
    },
    "gitlab_ci": {
        "name": "GitLab CI",
        "category": "DevOps",
        "description": "CI/CD GitLab",
        "generator": "gitlab_ci",
        "arch": "Pipeline",
        "testing": "None",
        "ci": "None",
    },
    "argocd": {
        "name": "ArgoCD",
        "category": "DevOps",
        "description": "GitOps Kubernetes",
        "generator": "argocd",
        "arch": "GitOps",
        "testing": "None",
        "ci": "None",
    },
    "crossplane": {
        "name": "Crossplane",
        "category": "DevOps",
        "description": "Control plane Kubernetes",
        "generator": "crossplane",
        "arch": "Control Plane",
        "testing": "None",
        "ci": "None",
    },
    # === CLOUD / IAAS (12) ===
    "aws_cdk": {
        "name": "AWS CDK TypeScript",
        "category": "Cloud",
        "description": "IaC AWS CDK",
        "generator": "aws",
        "arch": "IaC",
        "testing": "AWS CDK Asserts",
        "ci": "GitHub Actions",
    },
    "aws_cdk_python": {
        "name": "AWS CDK Python",
        "category": "Cloud",
        "description": "IaC AWS CDK Python",
        "generator": "aws",
        "arch": "IaC",
        "testing": "AWS CDK Asserts",
        "ci": "GitHub Actions",
    },
    "aws_cdk_go": {
        "name": "AWS CDK Go",
        "category": "Cloud",
        "description": "IaC AWS CDK Go",
        "generator": "aws",
        "arch": "IaC",
        "testing": "AWS CDK Asserts",
        "ci": "GitHub Actions",
    },
    "aws_sam": {
        "name": "AWS SAM",
        "category": "Cloud",
        "description": "Serverless AWS SAM",
        "generator": "aws_sam",
        "arch": "Serverless",
        "testing": "AWS SAM Test",
        "ci": "GitHub Actions",
    },
    "aws_cdk_v2": {
        "name": "AWS CDK v2",
        "category": "Cloud",
        "description": "AWS CDK v2 stable",
        "generator": "aws",
        "arch": "IaC",
        "testing": "AWS CDK Asserts",
        "ci": "GitHub Actions",
    },
    "azure_bicep": {
        "name": "Azure Bicep",
        "category": "Cloud",
        "description": "IaC Azure Bicep",
        "generator": "azure",
        "arch": "IaC",
        "testing": "Bicep Test",
        "ci": "GitHub Actions",
    },
    "azure_arm": {
        "name": "Azure ARM",
        "category": "Cloud",
        "description": "IaC Azure ARM",
        "generator": "azure",
        "arch": "IaC",
        "testing": "None",
        "ci": "GitHub Actions",
    },
    "azure_cd": {
        "name": "Azure Developer CLI",
        "category": "Cloud",
        "description": "Azure Developer CLI",
        "generator": "azure",
        "arch": "IaC",
        "testing": "None",
        "ci": "GitHub Actions",
    },
    "gcp_terraform": {
        "name": "GCP Terraform",
        "category": "Cloud",
        "description": "IaC GCP Terraform",
        "generator": "gcp",
        "arch": "IaC",
        "testing": "Terratest",
        "ci": "GitHub Actions",
    },
    "gcp_cloudfunctions": {
        "name": "GCP Cloud Functions",
        "category": "Cloud",
        "description": "Functions GCP 2nd gen",
        "generator": "gcp_functions",
        "arch": "Serverless",
        "testing": "Google Cloud Test",
        "ci": "GitHub Actions",
    },
    "gcp_cloudrun": {
        "name": "GCP Cloud Run",
        "category": "Cloud",
        "description": "Container serverless",
        "generator": "gcp",
        "arch": "Serverless",
        "testing": "None",
        "ci": "GitHub Actions",
    },
    "digitalocean": {
        "name": "DigitalOcean",
        "category": "Cloud",
        "description": "Droplets DO con Terraform",
        "generator": "digitalocean",
        "arch": "IaC",
        "testing": "Terratest",
        "ci": "GitHub Actions",
    },
    # === BASE DE DATOS (8) ===
    "postgresql": {
        "name": "PostgreSQL",
        "category": "Base de Datos",
        "description": "Base de datos PostgreSQL",
        "generator": "postgres",
        "arch": "RDBMS",
        "testing": "None",
        "ci": "Docker Compose",
    },
    "postgresql_timescale": {
        "name": "PostgreSQL TimescaleDB",
        "category": "Base de Datos",
        "description": "Time-series PostgreSQL",
        "generator": "postgres",
        "arch": "Time-series",
        "testing": "None",
        "ci": "Docker Compose",
    },
    "mongodb": {
        "name": "MongoDB",
        "category": "Base de Datos",
        "description": "Base de datos MongoDB",
        "generator": "mongodb",
        "arch": "Document",
        "testing": "None",
        "ci": "Docker Compose",
    },
    "mongodb_atlas": {
        "name": "MongoDB Atlas",
        "category": "Base de Datos",
        "description": "MongoDB cloud",
        "generator": "mongodb",
        "arch": "Document",
        "testing": "None",
        "ci": "None",
    },
    "redis": {
        "name": "Redis",
        "category": "Base de Datos",
        "description": "Cache/Message broker",
        "generator": "redis",
        "arch": "In-memory",
        "testing": "None",
        "ci": "Docker Compose",
    },
    "mysql": {
        "name": "MySQL",
        "category": "Base de Datos",
        "description": "Base de datos MySQL",
        "generator": "mysql",
        "arch": "RDBMS",
        "testing": "None",
        "ci": "Docker Compose",
    },
    "dynamodb": {
        "name": "DynamoDB",
        "category": "Base de Datos",
        "description": "NoSQL AWS",
        "generator": "dynamodb",
        "arch": "NoSQL",
        "testing": "None",
        "ci": "None",
    },
    "cockroachdb": {
        "name": "CockroachDB",
        "category": "Base de Datos",
        "description": "Distributed SQL",
        "generator": "cockroachdb",
        "arch": "Distributed",
        "testing": "None",
        "ci": "Docker Compose",
    },
    # === DATA / ML (7) ===
    "python_pandas": {
        "name": "Python Pandas",
        "category": "Data/ML",
        "description": "Data analysis Python",
        "generator": "python_ml",
        "arch": "Data Frame",
        "testing": "Pytest",
        "ci": "GitHub Actions",
    },
    "python_pytorch": {
        "name": "Python PyTorch",
        "category": "Data/ML",
        "description": "Deep learning PyTorch",
        "generator": "python_ml",
        "arch": "Neural Net",
        "testing": "Pytest",
        "ci": "GitHub Actions",
    },
    "python_tensorflow": {
        "name": "Python TensorFlow",
        "category": "Data/ML",
        "description": "ML TensorFlow",
        "generator": "python_ml",
        "arch": "Neural Net",
        "testing": "Pytest",
        "ci": "GitHub Actions",
    },
    "python_scikit": {
        "name": "Python Scikit-learn",
        "category": "Data/ML",
        "description": "ML clásico Python",
        "generator": "python_ml",
        "arch": "ML",
        "testing": "Pytest",
        "ci": "GitHub Actions",
    },
    "python_jupyter": {
        "name": "Jupyter Notebook",
        "category": "Data/ML",
        "description": "Notebooks Jupyter",
        "generator": "python_ml",
        "arch": "Notebook",
        "testing": "None",
        "ci": "GitHub Actions",
    },
    "python_mlflow": {
        "name": "MLflow",
        "category": "Data/ML",
        "description": "ML lifecycle tools",
        "generator": "python_ml",
        "arch": "MLOps",
        "testing": "None",
        "ci": "GitHub Actions",
    },
    "python_kafka": {
        "name": "Apache Kafka",
        "category": "Data/ML",
        "description": "Event streaming",
        "generator": "kafka",
        "arch": "Event Stream",
        "testing": "None",
        "ci": "Docker Compose",
    },
    # === MICROSERVICIOS / MESH (5) ===
    "grpc": {
        "name": "gRPC",
        "category": "Microservicios",
        "description": "RPC framework",
        "generator": "grpc",
        "arch": "IDL-based",
        "testing": "Go test",
        "ci": "GitHub Actions",
    },
    "graphql": {
        "name": "GraphQL Apollo",
        "category": "Microservicios",
        "description": "API GraphQL",
        "generator": "graphql",
        "arch": "Schema-first",
        "testing": "Jest",
        "ci": "GitHub Actions",
    },
    "istio": {
        "name": "Istio",
        "category": "Microservicios",
        "description": "Service mesh K8s",
        "generator": "istio",
        "arch": "Service Mesh",
        "testing": "None",
        "ci": "None",
    },
    "envoy": {
        "name": "Envoy",
        "category": "Microservicios",
        "description": "Proxy/service mesh",
        "generator": "envoy",
        "arch": "Proxy",
        "testing": "None",
        "ci": "None",
    },
    "nats": {
        "name": "NATS",
        "category": "Microservicios",
        "description": "Messaging system",
        "generator": "nats",
        "arch": "Pub/Sub",
        "testing": "None",
        "ci": "Docker Compose",
    },
}


def get_framework_list() -> Dict[str, Dict]:
    return FRAMEWORK_TEMPLATES


def get_frameworks_by_category() -> Dict[str, Dict[str, Dict]]:
    categories = {}
    for key, value in FRAMEWORK_TEMPLATES.items():
        cat = value["category"]
        if cat not in categories:
            categories[cat] = {}
        categories[cat][key] = value
    return categories


def get_categories() -> list:
    return list(set(v["category"] for v in FRAMEWORK_TEMPLATES.values()))


def get_generator(framework: str) -> Optional[Callable]:
    from src.templates.frameworks import (
        generate_nodejs_template,
        generate_nextjs_template,
        generate_python_template,
        generate_go_template,
        generate_rust_template,
        generate_dotnet_template,
        generate_docker_template,
        generate_kubernetes_template,
        generate_ansible_template,
        generate_aws_template,
        generate_azure_template,
        generate_gcp_template,
        generate_terraform_template,
        generate_solidity_template,
        generate_react_template,
        generate_vue_template,
        generate_svelte_template,
        generate_flutter_template,
        generate_react_native_template,
        generate_postgres_template,
        generate_scala_template,
        generate_java_template,
        generate_kotlin_template,
        generate_php_template,
        generate_ruby_template,
        generate_angular_template,
        generate_alpine_template,
        generate_htmx_template,
        generate_ionic_template,
        generate_capacitor_template,
        generate_elixir_template,
        generate_haskell_template,
        generate_nim_template,
        generate_dart_template,
        generate_go_template,
        generate_cpp_template,
        generate_swift_ios_template,
        generate_terraform_module,
        generate_mongodb_template,
        generate_redis_template,
        generate_mysql_template,
        generate_k8s_helm,
        generate_k8s_argo,
        generate_github_actions_template,
        generate_gitlab_ci_template,
        generate_jenkins_template,
        generate_ml_template,
        generate_kafka_template,
        generate_nats_template,
        generate_envoy_template,
        generate_istio_template,
        generate_crossplane_template,
        generate_vault_template,
        generate_terragrunt_template,
        generate_packer_template,
        generate_kustomize_template,
    )

    generators = {
        "nodejs": generate_nodejs_template,
        "nextjs": generate_nextjs_template,
        "python": generate_python_template,
        "python_ml": generate_python_template,
        "go": generate_go_template,
        "golang": generate_go_template,
        "rust": generate_rust_template,
        "dotnet": generate_dotnet_template,
        "scala": generate_scala_template,
        "java": generate_java_template,
        "kotlin": generate_kotlin_template,
        "kotlin_android": generate_kotlin_template,
        "php": generate_php_template,
        "ruby": generate_ruby_template,
        "elixir": generate_elixir_template,
        "haskell": generate_haskell_template,
        "nim": generate_nim_template,
        "dart": generate_dart_template,
        "cpp": generate_cpp_template,
        "solidity": generate_solidity_template,
        "rust_substrate": generate_rust_template,
        "solana": generate_solidity_template,
        "near": generate_solidity_template,
        "algorand": generate_solidity_template,
        "cardano": generate_solidity_template,
        "docker": generate_docker_template,
        "docker_compose": generate_docker_template,
        "kubernetes": generate_kubernetes_template,
        "helm": generate_k8s_helm,
        "kustomize": generate_kustomize_template,
        "ansible": generate_ansible_template,
        "terraform": generate_terraform_template,
        "terragrunt": generate_terragrunt_template,
        "packer": generate_packer_template,
        "vault": generate_vault_template,
        "jenkins": generate_jenkins_template,
        "github_actions": generate_github_actions_template,
        "gitlab_ci": generate_gitlab_ci_template,
        "argocd": generate_k8s_argo,
        "crossplane": generate_crossplane_template,
        "aws": generate_aws_template,
        "aws_sam": generate_aws_template,
        "azure": generate_azure_template,
        "gcp": generate_gcp_template,
        "gcp_functions": generate_gcp_template,
        "digitalocean": generate_terraform_module,
        "postgres": generate_postgres_template,
        "postgresql": generate_postgres_template,
        "mongodb": generate_mongodb_template,
        "redis": generate_redis_template,
        "mysql": generate_mysql_template,
        "dynamodb": generate_terraform_module,
        "cockroachdb": generate_postgres_template,
        "react": generate_react_template,
        "vue": generate_vue_template,
        "svelte": generate_svelte_template,
        "angular": generate_angular_template,
        "solid": generate_react_template,
        "alpine": generate_alpine_template,
        "htmx": generate_htmx_template,
        "qwik": generate_react_template,
        "flutter": generate_flutter_template,
        "react_native": generate_react_native_template,
        "expo": generate_react_native_template,
        "ionic": generate_ionic_template,
        "capacitor": generate_capacitor_template,
        "swift_ios": generate_swift_ios_template,
        "tauri": generate_react_template,
        "mlflow": generate_ml_template,
        "kafka": generate_kafka_template,
        "nats": generate_nats_template,
        "envoy": generate_envoy_template,
        "istio": generate_istio_template,
    }

    fw = FRAMEWORK_TEMPLATES.get(framework, {})
    gen_key = fw.get("generator")

    if gen_key in generators:
        return generators[gen_key]
    return None
